dist: xenial
services:
  - xvfb
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

language: java
sudo: false
script: mvn -Dmaven.test.skip=true package


deploy:
  provider: releases
  api_key:
    secure: "8fe8149945616cf56ac35eb3d7c72ba64c7683c2"
  file: "target/libmanager-v3-1.0-SNAPSHOT-jar-with-dependencies.jar"
  skip_cleanup: true
